run:
  timeout: 2m
  concurrency: 4
  allow-parallel-runners: true
  modules-download-mode: readonly
  skip-dirs:
    - vendor
issues:
  max-same-issues: 0
linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - unused
    - exportloopref
  disable:
    - gocritic
    - ruleguard
linters-settings:
  staticcheck:
    checks: ["all"]
